java PosicaoDaLetra < input/file0 > output/file0
java PosicaoDaLetra < input/file1 > output/file1
java PosicaoDaLetra < input/file2 > output/file2
java PosicaoDaLetra < input/file3 > output/file3
java PosicaoDaLetra < input/file4 > output/file4
java PosicaoDaLetra < input/file5 > output/file5
java PosicaoDaLetra < input/file6 > output/file6
java PosicaoDaLetra < input/file7 > output/file7
java PosicaoDaLetra < input/file8 > output/file8
java PosicaoDaLetra < input/file9 > output/file9
java PosicaoDaLetra < input/file10 > output/file10
java PosicaoDaLetra < input/file11 > output/file11
java PosicaoDaLetra < input/file12 > output/file12
java PosicaoDaLetra < input/file13 > output/file13
java PosicaoDaLetra < input/file14 > output/file14
java PosicaoDaLetra < input/file15 > output/file15
java PosicaoDaLetra < input/file16 > output/file16
java PosicaoDaLetra < input/file17 > output/file17
java PosicaoDaLetra < input/file18 > output/file18
java PosicaoDaLetra < input/file19 > output/file19
java PosicaoDaLetra < input/file20 > output/file20
java PosicaoDaLetra < input/file21 > output/file21
java PosicaoDaLetra < input/file22 > output/file22
java PosicaoDaLetra < input/file23 > output/file23
java PosicaoDaLetra < input/file24 > output/file24
java PosicaoDaLetra < input/file25 > output/file25
